# Generated by Django 3.1.7 on 2022-05-26 03:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='recentsearches',
            options={'verbose_name_plural': 'RecentSearches'},
        ),
        migrations.CreateModel(
            name='AddedRecipe',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ingredients', models.TextField()),
                ('steps', models.TextField()),
                ('readyInMinutes', models.PositiveIntegerField(default=10)),
                ('food_cat', models.CharField(max_length=10)),
                ('image', models.ImageField(upload_to='')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
