# Generated by Django 3.1.7 on 2022-05-26 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_addedrecipe_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addedrecipe',
            name='image',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
