# Generated by Django 3.1.7 on 2022-05-26 08:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_auto_20220526_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='addedrecipe',
            name='healthScore',
            field=models.PositiveIntegerField(default=10),
        ),
    ]
