# Generated by Django 3.1.7 on 2022-05-26 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0007_review'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addedrecipe',
            name='youTubeId',
            field=models.TextField(blank=True, null=True),
        ),
    ]
