# Generated by Django 3.1.7 on 2022-05-26 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0008_auto_20220526_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='addedrecipe',
            name='approval',
            field=models.CharField(choices=[('approved', 'approved'), ('rejected', 'rejected'), ('pending', 'pending')], default='pending', max_length=20),
        ),
    ]
