# Generated by Django 3.1.7 on 2022-05-26 14:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0009_addedrecipe_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='addedrecipe',
            name='timestamp',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 5, 26, 19, 39, 34, 47046)),
            preserve_default=False,
        ),
    ]
