# Generated by Django 3.1.7 on 2022-05-26 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0010_addedrecipe_timestamp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='addedrecipe',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
