# Generated by Django 3.1.7 on 2022-05-27 15:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('donate', '0002_auto_20220527_2020'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='RecipeDonate',
            new_name='FoodDonate',
        ),
        migrations.CreateModel(
            name='RequestFood',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('food', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='donate.fooddonate')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
