# Generated by Django 3.1.7 on 2022-05-28 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0003_auto_20220527_2056'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestfood',
            name='approval',
            field=models.CharField(choices=[('approved', 'approved'), ('rejected', 'rejected'), ('pending', 'pending')], default='pending', max_length=20),
        ),
    ]
