# Generated by Django 3.1.7 on 2022-05-28 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donate', '0004_requestfood_approval'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestfood',
            name='no_of_people',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
