# Generated by Django 3.1.1 on 2021-03-16 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='pincode',
            field=models.CharField(max_length=6),
        ),
    ]
